on: pull_request

jobs:
  check-branch-is-staged:
    name: Check the branch is staged before it can be merged
    runs-on: ubuntu-latest
    steps:
      - uses: jack-lewin/check-staged@main
        with:
          staging-branch: 'dev'
